### ISSUE TITLE
Crash server 1.12.2

### ISSUE THREAD

**Issue by Makalat** [RootsTeam/AdventureBags#6]
I don't know why an error occurred. Mod has an error on the server
server crash report:
https://github.com/RootsTeam/AdventureBags/files/1620815/crash-2018-01-11_01.04.40-server.txt

**Comment by DEFALTPANDA** [comment]
Yea, I'm getting the same issue. This line gives it away that it is a problem with client KeyBinding trying to bind on a server which has no support for key binds. 

Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/settings/KeyBinding
	at sirshadow.adventurebags.common.utils.handler.KeyBindings.<init>

**Comment by DaemonUmbra** [comment]
The issue is that [this](https://github.com/ShadowGamerXY/AdventureBags/blob/22b59c84b8dc41a204e8ddd944aea731f60d6970/src/main/java/sirshadow/adventurebags/proxys/CommonProxy.java#L33) and [this](https://github.com/ShadowGamerXY/AdventureBags/blob/22b59c84b8dc41a204e8ddd944aea731f60d6970/src/main/java/sirshadow/adventurebags/proxys/CommonProxy.java#L55-L61) should be in ClientProxy, not CommonProxy.

**Comment by ShadowGamerXY** [comment]
Fixed in the 0.8 update.
